spring:
  application:
    name: gateway-server
  profiles:
    active: assembly,plugin,dev

zuul:
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
feign:
  hystrix:
    enabled: true
