spring:
  application:
    name: gateway-server
  profiles:
    active: dev,plugin,cloud-dev,assembly-dev,api-dev

zuul:
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
  host:
    connection-request-timeout-millis: 10000
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000

feign:
  hystrix:
    enabled: true


shiro:
  sessionIdName: token
  sessionTimeout: 7200000