eureka:
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka/
server:
  port: 8105
  servlet:
    context-path: /

spring:
  datasource:
    druid:
      min-idle: 1
      test-on-borrow: true
      stat-view-servlet:
        allow: true
      max-active: 20
      initial-size: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.92.6.56:3306/share_mall?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: xm123456
  rabbitmq:
    host: 47.92.6.56
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual  #消费确认置为手动
  redis:
    host: 47.92.6.56
    port: 6379
    password: kxy521yu
    database: 0
    timeout: 25000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  zipkin:
    base-url: http://47.92.6.56:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
logging:
  logPath: D:\java\data\log\share\api-mall
  logLevel: debug

tx-lcn:
  client:
    manager-address: 47.92.6.56:8070

pdd:
  client-id: 022c61074e3d46dd946a45f3024a75d8
  client-secret: 702bee4684121e512392cb0405b9292fbc624234