server:
  port: 8105

spring:
  datasource:
    druid:
      min-idle: 1
      test-on-borrow: true
      stat-view-servlet:
        allow: true
      max-active: 20
      initial-size: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/share_mall?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: kxy521yu

#阿里云OSS文件管理
oss:
  ali:
    endpoint: oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI4Fsu8LS6dfkSgk9qe6h1
    accessKeySecret: epYBonCerRq2V1QWR6CJ5yaFfjg1A5
    bucketName: mall-share

pdd:
  client-id: 022c61074e3d46dd946a45f3024a75d8
  client-secret: 702bee4684121e512392cb0405b9292fbc624234

logging:
  logPath: /data/share/api-mall
  logLevel: debug
