server:
  port: 8105

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.92.6.56:3306/share_mall?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: xm123456

logging:
  logPath: D:\java\data\log\share\api-mall
  logLevel: debug
