spring:
  application:
    name: api-user
  profiles:
    active: assembly-dev,plugin,dev

wx:
  appId: wx77c95d4a2f1bfab0
  secret: 149a2853db7a9aa718aca580b0883fbb
#  token: GiOleLZJjps03G4dLq3Ogj0ooT2d3DKI
#  encodingAESKey: y45Ljp45d5DQIt42TzL0iJPZePDoeIjd5jHoTQEQLe2
