eureka:
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka/
server:
  port: 8107
  servlet:
    context-path: /

spring:
  datasource:
    druid:
      min-idle: 1
      test-on-borrow: true
      stat-view-servlet:
        allow: true
      max-active: 20
      initial-size: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.211.37.193:3306/share_user?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: kxy521yu
#  rabbitmq:
#    host: 129.211.37.193
#    port: 5672
#    username: guest
#    password: guest
#    listener:
#      simple:
#        acknowledge-mode: manual  #消费确认置为手动
#  redis:
#    host: 129.211.37.193
#    port: 6379
#    password: kxy521yu
#    database: 0
#    timeout: 25000
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0

logging:
  logPath: /data/log/share/api-user
  logLevel: info
