spring:
  application:
    name: cron-service
  profiles:
    active: dev,plugin,cloud-dev,assembly-dev,api-dev

pdd:
  client-id: 022c61074e3d46dd946a45f3024a75d8
  client-secret: 702bee4684121e512392cb0405b9292fbc624234