#组件配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8101/eureka/

spring:
  rabbitmq:
    host: 47.92.6.56
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual  #消费确认置为手动
  redis:
    host: 47.92.6.56
    port: 6379
    password: kxy521yu
    database: 0
    timeout: 25000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  #链路追踪服务配置
  zipkin:
    base-url: http://47.92.6.56:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

#分布式事务
tx-lcn:
  client:
    manager-address: 47.92.6.56:8070

#阿里云OSS文件管理
oss:
  ali:
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI4Fsu8LS6dfkSgk9qe6h1
    accessKeySecret: epYBonCerRq2V1QWR6CJ5yaFfjg1A5
    bucketName: mall-share
