server:
  port: 8112

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.92.6.56:3306/share_pay?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: xm123456

logging:
  logPath: D:\java\data\log\share\api-pay
  logLevel: debug

wx:
  pay:
    appId: wxd14f92d77787943c
    mchId: 1572782521
    mchKey: 71f2381fb0a1d9f79e3085f9543a9188
    keyPath: classpath:cert/apiclient_cert.p12
    notifyUrl: http://xiaomujiayou.w3.luyouxia.net/api-pay/pay/wx/order/notify